apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: api-gateway
build:
  artifacts:
  - image: hub.pirat.app/api-gateway
    docker:
      dockerfile: fast.Dockerfile
deploy:
  kubectl:
    defaultNamespace: dev
    manifests:
    - k8s/configmap.yaml
    - k8s/roles.yaml
    - k8s/deployment.yaml
