apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  services.yaml: |
    version: v1
    services:
        - name: iam-authorization
          serviceUrl: iam-authorization-service:8080
          paths:
            - /api/v1/iam/
            - /api/v2/iam/
        - name: cart
          serviceUrl: cart-service:8080
          paths:
            - /api/v1/cart
            - /api/v2/cart
            - /api/v1/discount
            - /api/v2/discount
        - name: iam-management
          serviceUrl: iam-management-service:8080
          paths:
            - /connect
            - /account/confirmemail
            - /account/logout
            - /api/v1/iam-management
            - /api/v2/iam-management
            - /api/v2/iam-management/partner/me/config
            - /.well-known/openid-configuration
        - name: product-catalog
          serviceUrl: product-catalog-service:8080
          paths:
            - /api/v1/productcatalog
        - name: payment
          serviceUrl: payment-service:8080
          paths:
            - /api/v1/payment
        - name: language
          serviceUrl: language-service:8080
          paths: 
            - /api/v1/language
        - name: venue
          serviceUrl: venue-service:8080
          paths:
            - /api/v1/venue
            - /api/v2/venue
        - name: ticket
          serviceUrl: ticket-service:8080
          paths:
            - /api/v1/ticket
            - /api/v2/ticket
        - name: selection
          serviceUrl: selection-service:8080
          paths:
            - /api/v1/selection
            - /api/v2/selection
        - name: card
          serviceUrl: card-api-service:8080
          paths:
            - /api/v1/card/
