apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: 1.0.0
    spec:
      containers:
      - name: api-gateway
        image: hub.pirat.app/api-gateway
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: gateway
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    name: http-gateway
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: gateway
  name: api-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    name: api-gateway
spec:
  tls:
    - hosts:
      - api.devopshaven.com
      secretName: api-dh-tls
  rules:
  - host: api.devopshaven.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
